### ISSUE TITLE
Can you guys show me the part that fix SSR?

### ISSUE THREAD

**Issue by bjrmatos** [sketchpixy/react-ssr-temp-fix#1]
Hello guys! i'm using rubix template (v3.0.5) and i'm curious to know what is the actual patch that fix SSR, can you point me where it is? ..the commit log doesn't tell me anything :(

**Comment by shripadk** [comment]
@bjrmatos You can see the patch here: https://github.com/shripadk/react/commit/4d12c9baeafdfa2a36242ee92aa1de5e46a48a53

We are going to use official React 0.14 in the next release anyways because this bug has been fixed.

**Comment by bjrmatos** [comment]
excellent news! according to your tests, it is really fixed in 0.14? (I only ask because facebook/react#3620 is still open)
